### ISSUE TITLE
[crystal branch/Python3.10.8] - aliases deprecated in Numpy 1.20 

### ISSUE THREAD

**Issue by rosamanukjan** [mueller-lab/PyFRAP#3]
When initiating the analysis of a molecule, the selection of an ROI (radial slice) and processing of the indexing can't progress, due to deprecated aliases:

1) Selecting "radial Slice", within Wizard: Error in \modules\__init__.py (line 1705)

"AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases were originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"

2) Initiation of indexing: Error in \modules\pyfrp_idx_module.py (lines 328f)

"AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases were originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"

**Comment by muenalan** [comment]
The current crystal branch does not contain the mentioned files. Are you sure you used the up-to-date version? Nonetheless, I have fixed the issue and pushed a new commit.

Could you test the newest version [commit 7e0057b] ?

**Comment by rosamanukjan** [comment]
The first error, mentioned above, actually occured from "pyfrp_misc_module.py", as you have solved already. Thanks. 
Regarding the second error, the file "pyfrp_idx_module.py" exists within the same directory. You applied changes to the file underneath. Still, the error occurs when PyFRAP initiates indexing.

**Comment by muenalan** [comment]
Updated pyfrp_idx_module.py [commit b882833].

Let me know if you if this solved the issue.

**Comment by rosamanukjan** [comment]
New issue arises, with 

"  File "\Python310\site-packages\pyfrp\modules\pyfrp_idx_module.py", line 329, in <listcomp>
    c=np.array([np.cdouble(xc,yc) for xc,yc in zip(x,y)])
TypeError: function takes at most 1 argument (2 given)"

The indexing is not even able to initiate.

**Comment by muenalan** [comment]
Switched to builtin "complex()" [8a57058]
